Repository portato-io/portatoapp, pull requests merged in 2023-12, with the labels that each got.

#314 Map works when signed out
  src/Pages/PortatoMap.tsx
Labels: backend, frontend, dependency-update, size XS

#301 Dev/siginin
  public/loading-spinner.png
  src/CSS/Core.css
  src/CSS/Fonts.css
  src/CSS/Forms.css
  src/CSS/Icons.css
  src/CSS/Mediaqueries.css
  src/Components/FirebaseAuth.tsx
  src/Components/authentification/formDefinition.ts
  src/Components/authentification/initialStep.tsx
  src/Components/authentification/passwordReset.tsx
  src/Components/authentification/signUpStep.tsx
  src/Components/authentification/signedUpStep.tsx
  src/Components/authentification/smsSent.tsx
  src/Pages/Driver/RouteSummary.tsx
  src/Pages/Menu.tsx
  src/Pages/Sender/RequestSummary.tsx
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
  src/global.d.ts
  src/type.ts
Labels: frontend, size M, size L

#318 Map refactoring
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  public/index.html
  public/loading-spinner.png
  src/Assets/Images/team/moritz.webp
  src/CSS/Core.css
  src/CSS/Fonts.css
  src/CSS/Forms.css
  src/CSS/Icons.css
  src/CSS/Mediaqueries.css
  src/Components/FetchDeals.tsx
  src/Components/FetchRequests.tsx
  src/Components/FirebaseAuth.tsx
  src/Components/Map.tsx
  src/Components/authentification/formDefinition.ts
  src/Components/authentification/initialStep.tsx
  src/Components/authentification/passwordReset.tsx
  src/Components/authentification/signUpStep.tsx
  src/Components/authentification/signedUpStep.tsx
  src/Components/authentification/smsSent.tsx
  src/Pages/Driver/RouteSummary.tsx
  src/Pages/Home.tsx
  src/Pages/Menu.tsx
  src/Pages/PortatoMap.tsx
  src/Pages/Profile/Support/ContactDriver.tsx
  src/Pages/Sender/EnterRequestAddress.tsx
  src/Pages/Sender/RequestSummary.tsx
  src/Store/reducers/DealReducer.ts
  src/Store/reducers/RequestReducer.ts
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
  src/global.d.ts
  src/index.tsx
  src/linksStoreToFirebase.js
  src/service-worker.ts
  src/type.ts
Labels: backend, frontend, size M, size XL

#317 checkbox for terms and button disabled
  src/Components/authentification/signUpStep.tsx
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
  src/service-worker.ts
Labels: size M, size XS, size S

#320 Feature/termsandconditions
  src/Components/authentification/signUpStep.tsx
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
Labels: size S

#302 Dev/signin/styles
  src/CSS/Fonts.css
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
Labels: frontend, size M, size XS

#309 Added more padding around logo
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/logo1024.png
  public/logo256.png
  public/logo_green.png
Labels: size XS

#322 fixes translation
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
Labels: size XS

#321 Fix/mandatory date
  src/Components/PageComponents/SingleTripContent.tsx
  src/Pages/Profile/MyAccount.tsx
  src/Pages/Profile/Settings.tsx
  src/Pages/Sender/EnterRequestSizeWeightImage.tsx
  src/Pages/Sender/EnterRequestTime.tsx
Labels: size M
