Repository portato-io/portatoapp, pull requests merged in 2023-10, with the labels that each got.

#277 route confirmation email
  src/Components/FirebaseAuth.tsx
  src/Pages/Driver/RouteSummary.tsx
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
  src/linksStoreToFirebase.js
Labels: backend, size M

#278 Hotfix: google tags triggered with navbar icons and imprint change
  src/Components/BottomBar.tsx
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
Labels: size XS

#280 Css/cleanup
  src/Assets/Images/portato-landing-14.svg
  src/CSS/Core.css
  src/CSS/Fonts.css
  src/CSS/Forms.css
  src/CSS/Home.css
  src/CSS/Mediaqueries.css
  src/CSS/Profile.css
  src/Pages/FAQ.tsx
  src/Pages/Home.tsx
  src/Pages/Imprint.tsx
  src/Pages/Layouts/PageLayoutTest.tsx
  src/Pages/PrivacyPolicy.tsx
  src/Pages/Sender/EnterRequestPrice.tsx
  src/Pages/Sender/RequestSummary.tsx
  src/Pages/TermsAndConditions.tsx
  src/Translation/English/translation.json
  src/Translation/French/translation.json
  src/Translation/German/translation.json
Labels: frontend, size L

#279 Design/header
  src/CSS/Core.css
  src/CSS/Fonts.css
  src/CSS/Navigation.css
  src/Components/HeaderBar.tsx
  src/Pages/Home.tsx
  src/Pages/Layouts/PageLayoutTest.tsx
Labels: frontend, size L

#283 Moved top margin to layout-wrapper class.
  src/CSS/Core.css
Labels: frontend, size XS

#284 Adding meta pixel to allow for FB/IG advertising
  public/index.html
Labels: size XS

#285 adds increment script for ci
  .github/workflows/firebase-hosting-merge.yml
  increment-version.js
Labels: backend, size XS

#286 Automated Ci versioning fix
  .github/workflows/firebase-hosting-merge.yml
  src/service-worker.ts
Labels: backend, size XS

#293 fixes manifest path
  public/index.html
Labels: size XS

#296 fixes maskable icon for PWA
  public/manifest.json
Labels: size XS

#295 Minor changes, to improve SEO rating
  src/Pages/Home.tsx
Labels: size XS
